### ISSUE TITLE
Cannot use scoped service with SoapCore version 1.1.0.50

### ISSUE THREAD

**Issue by marcmognol** [DigDes/SoapCore#1085]
# Issue

Since I've updated my project dependency SoapCore to version 1.1.0.50, SoapCore isn't able to resolve Scoped or Transient registered service.

Did I miss anything?

Thanks.

## Workaround

If I rollback to version 1.1.0.49, everything is working well.

## Logs

```
fail: SoapCore.SoapEndpointMiddleware[0]
      An error occurred processing the message
      System.InvalidOperationException: Cannot resolve scoped service 'Interfaces.IReportService' from root provider.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at SoapCore.SoapEndpointMiddleware`1.ProcessMessage(Message requestMessage, SoapMessageEncoder messageEncoder, IAsyncMessageFilter[] asyncMessageFilters, HttpContext httpContext, IServiceProvider serviceProvider) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 527
         at SoapCore.SoapEndpointMiddleware`1.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 328
```
In SoapEndpointMiddleware.cs file:

![image](https://github.com/user-attachments/assets/49e30335-13bf-49c0-92f5-da41e1a2d0f4)

**Comment by andersjonsson** [comment]
Hopefully I've fixed this issue in #1086
I'll leave this open until you've had the chance to test and confirm

**Comment by marcmognol** [comment]
Hi @andersjonsson ,

Thank you for your quick support on this. Yes it works better with your commit.

Marc

**Comment by andersjonsson** [comment]
Thank you for confirming!
