### ISSUE TITLE
Similar issue to issue #90 "Sequence contains no elements"

### ISSUE THREAD

**Issue by jphellemons** [DigDes/SoapCore#186]
Hi I have a similar issue like: https://github.com/DigDes/SoapCore/issues/90

>System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at SoapCore.MetaMessage.OnWriteStartEnvelope(XmlDictionaryWriter writer)

In my startup.cs:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSoapCore();
        services.TryAddSingleton<IFileController, FileController>();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
        binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
        app.UseSoapEndpoint<IFileController>("/MyUpload.asmx", binding, SoapSerializer.XmlSerializer);
    }

My IFileController.cs is almost empty:

    public interface IFileController
    {
        
    }

And my FileController.cs:

    [ServiceContract]
    public class FileController : IFileController
    {
        public FileController()
        {
            System.Diagnostics.Debug.WriteLine("test");
        }

        [OperationContract]
        public string Ping(string s)
        {
            Console.WriteLine("Exec ping method");
            return s;
        }
    }

I tried to use Postman to post to MyUpload.asmx or MyUpload.asmx/Ping?s=hello or MyUpload.asmx?Ping etc. but all return 404 or 500...

**Comment by jphellemons** [comment]
My bad, I has public class IFileController instead of an interface!
