### ISSUE TITLE
Unexpected End of File

### ISSUE THREAD

**Issue by AceCoderLaura** [DigDes/SoapCore#27]
When I hit my hosted service via a web browser, I get this exception:
```
System.Xml.XmlException: Unexpected end of file.
   at System.Xml.EncodingStreamWrapper.ReadBOMEncoding(Boolean notOutOfBand)
   at System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)
   at System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.TakeStreamedReader(Stream stream, Encoding enc)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.ReadMessage(Stream stream, Int32 maxSizeOfHeaders, String contentType)
   at SoapCore.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext()
```
It also happens when I use svcutil to extract metadata.

The service is unusable. What do I do?

**Comment by AceCoderLaura** [comment]
I've figured this out, it's a bug. I'll make a PR when it's ready.

**Comment by tpatikirikorala** [comment]
I got this error as well. What can we do about this?

**Comment by AceCoderLaura** [comment]
@tpatikirikorala I've forked this repo and put my fix in here:
https://github.com/AceCoderLaura/SoapCore

**Comment by kotovaleksandr** [comment]
Check package with your changes: https://www.nuget.org/packages/SoapCore/0.9.2
Thanks for help!
