### ISSUE TITLE
Error after upgrading to ASP.NET Core 3.0 Preview 7

### ISSUE THREAD

**Issue by IvanFarkas** [DigDes/SoapCore#293]
Getting error after upgrading to ASP.NET Core 3.0 Preview 7.

- Microsoft.AspNetCore.App 3.0.0-preview7.19365.7
- Microsoft.NETCore.App 3.0.0-preview7-27912-14
- .NET Core SDK 3.0.100-preview7-012821

```
11:29:43 [Error] () HTTP "POST" "/Service.svc" responded 500 in 2.7632 ms
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

The fix is just like for [Sentry](https://codecov.io/gh/getsentry/sentry-dotnet/pull/250/diff?src=pr&el=tree#diff-c3JjL1NlbnRyeS5Bc3BOZXRDb3JlL1NlbnRyeU1pZGRsZXdhcmUuY3M=)
By referencing the fixed dll instead of the NuGet package it works again.
```csharp
public async Task Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
{
	//httpContext.Request.EnableRewind();
	httpContext.Request.EnableBuffering();
```

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.9.8-alpha

**Comment by IvanFarkas** [comment]
Fantastic! Thx.
