### ISSUE TITLE
The Server from samples doesn't work when the reference is added as NuGet package

### ISSUE THREAD

**Issue by alexfdezsauco** [DigDes/SoapCore#707]
The Server from samples doesn't work when the reference is added as NuGet package. 

I try to make it work by adding the writeEncoding, then the error is about the version. But actually when it run doesn't work properly.  So, looks like the NuGet package is not sync with the sources in this repository.

Log:

    Application startup exception: System.ArgumentNullException: Value cannot be null. (Parameter 'writeEncoding')
       at SoapCore.MessageEncoder.SoapMessageEncoder..ctor(MessageVersion version, Encoding writeEncoding, XmlDictionaryReaderQuotas quotas, Boolean omitXmlDeclaration, Boolean indentXml)
       at SoapCore.SoapEndpointMiddleware`1..ctor(ILogger`1 logger, RequestDelegate next, SoapOptions options)
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
       at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
       at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
       at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint[T_MESSAGE](IEndpointRouteBuilder routes, Type type, String pattern, SoapEncoderOptions[] encoders, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, Binding binding, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint(IEndpointRouteBuilder routes, Type type, String pattern, SoapEncoderOptions[] encoders, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, Binding binding, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint[T](IEndpointRouteBuilder routes, String path, SoapEncoderOptions encoder, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at Server.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints) in D:\Workspaces\@archive\2021\SoapCore\samples\Server\Startup.cs:line 30
       at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
       at Server.Startup.Configure(IApplicationBuilder app) in D:\Workspaces\@archive\2021\SoapCore\samples\Server\Startup.cs:line 29
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
       at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
    crit: Microsoft.AspNetCore.Hosting.WebHost[6]
          Application startup exception
    System.ArgumentNullException: Value cannot be null. (Parameter 'writeEncoding')
       at SoapCore.MessageEncoder.SoapMessageEncoder..ctor(MessageVersion version, Encoding writeEncoding, XmlDictionaryReaderQuotas quotas, Boolean omitXmlDeclaration, Boolean indentXml)
       at SoapCore.SoapEndpointMiddleware`1..ctor(ILogger`1 logger, RequestDelegate next, SoapOptions options)
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
       at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
       at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
       at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint[T_MESSAGE](IEndpointRouteBuilder routes, Type type, String pattern, SoapEncoderOptions[] encoders, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, Binding binding, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint(IEndpointRouteBuilder routes, Type type, String pattern, SoapEncoderOptions[] encoders, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, Binding binding, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at SoapCore.SoapEndpointExtensions.UseSoapEndpoint[T](IEndpointRouteBuilder routes, String path, SoapEncoderOptions encoder, SoapSerializer serializer, Boolean caseInsensitivePath, ISoapModelBounder soapModelBounder, WsdlFileOptions wsdlFileOptions, Boolean indentXml, Boolean omitXmlDeclaration)
       at Server.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints) in D:\Workspaces\@archive\2021\SoapCore\samples\Server\Startup.cs:line 30
       at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
       at Server.Startup.Configure(IApplicationBuilder app) in D:\Workspaces\@archive\2021\SoapCore\samples\Server\Startup.cs:line 29
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
       at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
       at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()

**Comment by funkysi1701** [comment]
I had the same issue do you need to add SoapSerializer.XmlSerializer as a third parameter?

eg endpoints.UseSoapEndpoint<ServiceContractImpl>("/Service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer)

However this doesn't look to match what the docs says
