### ISSUE TITLE
DateOnly throws .NET type DateOnly cannot be resolved into XML schema type

### ISSUE THREAD

**Issue by kobruleht** [DigDes/SoapCore#793]
Trying to use .NET 6 DateOnly datatype throws  exception

```
System.ArgumentException: .NET type DateOnly cannot be resolved into XML schema type
SoapCore.Meta.MetaBodyWriter.ResolveType(Type type)
at SoapCore.Meta.MetaBodyWriter.AddSchemaType(XmlDictionaryWriter writer, TypeToBuild toBuild, String name, Boolean isArray, String namespace, Boolean isAttribute, Boolean isListWithoutWrapper, Boolean isUnqualified)
at SoapCore.Meta.MetaBodyWriter.AddSchemaTypePropertyOrField(XmlDictionaryWriter writer, MemberInfo member, TypeToBuild parentTypeToBuild)
at SoapCore.Meta.MetaBodyWriter.AddSchemaComplexType(XmlDictionaryWriter writer, TypeToBuild toBuild)
at SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
at SoapCore.Meta.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
at SoapCore.MessageEncoder.SoapMessageEncoder.WriteMessageAsync(Message message, PipeWriter pipeWriter)
at SoapCore.SoapEndpointMiddleware`1.ProcessMeta(HttpContext httpContext)
at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)

```

**Comment by andersjonsson** [comment]
Yup. I can see that there is no case for DateOnly in the ClrTypeResolver.
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/Meta/ClrTypeResolver.cs

Care to add one and submit a PR?

Full disclosure: I'm not a project maintainer. Just a user/contributor trying to help other users to contribute. That way we can all help to move this project forward.

**Comment by kobruleht** [comment]
I dont know the internals on SoapCore to properly implement this. However it looks like the patch would be trivial. Maybe someone with commit rights adds this and publishes new nuget package.
