### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by Ldoppea** [DigDes/SoapCore#90]
Hi,

I'm trying to use SoapCore, but i did not succeeded and get the following error when accessing my endpoint : 
`InvalidOperationException: Sequence contains no elements`

Here is what i'm doing : 
- File > New > Project > .Net Core > ASP.NET Core Web Application > API (Core 2.1)
- Install nuget package > SoapCore
- Create new class with following content : 
```
    public class ServicePing
    {
        public string Ping(string msg)
        {
            return string.Join(string.Empty, msg.Reverse());
        }
    }
```
- Edit Startup.cs as following : 
  - Add `services.AddSingleton(new ServicePing());` in `public void ConfigureServices(IServiceCollection services)`
  - Add `app.UseSoapEndpoint<ServicePing>(path: "/PingService.svc", binding: new BasicHttpBinding());` in `public void Configure(IApplicationBuilder app, IHostingEnvironment env)`
- Debug the program and try accessing `https://localhost:1337/PingService.svc`
- Following error is displayed : 
```
InvalidOperationException: Sequence contains no elements
System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
```

Here is the detailed StackTrace : 
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at SoapCore.MetaMessage.OnWriteStartEnvelope(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessagePreamble(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsync(Message message, Stream stream)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsyncInternal(Message message, Stream stream)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin(Task task)
   at SoapCore.SoapEndpointMiddleware.ProcessMeta(HttpContext httpContext)
   at SoapCore.SoapEndpointMiddleware.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Do you have any idea of what is the problem?

**Comment by Ldoppea** [comment]
Ok, my bad, I forgot to add `[ServiceContract]` and `[OperationContract]` on the ServicePing class and methods : 

```
    [ServiceContract]
    public class ServicePing
    {
        [OperationContract]
        public string Ping(string msg)
        {
            return string.Join(string.Empty, msg.Reverse());
        }
    }
```
