### ISSUE TITLE
unrecognized version.

### ISSUE THREAD

**Issue by d41z** [DigDes/SoapCore#971]
I created a web service using this library but when using consume it I receive this error:

<s:Envelope
	xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<s:Body>
		<s:Fault>
			<faultcode>s:Client</faultcode>
			<faultstring>Unrecognized version.</faultstring>
		</s:Fault>
	</s:Body>
</s:Envelope>

At the console:

fail: SoapCore.SoapEndpointMiddleware[0]
      An error occurred processing the message
      System.ServiceModel.CommunicationException: Unrecognized version.
         at System.ServiceModel.Channels.ReceivedMessage.ReadStartEnvelope(XmlDictionaryReader reader)
         at System.ServiceModel.Channels.StreamedMessage..ctor(XmlDictionaryReader reader, Int32 maxSizeOfHeaders, MessageVersion desiredVersion)
         at System.ServiceModel.Channels.Message.CreateMessage(XmlDictionaryReader envelopeReader, Int32 maxSizeOfHeaders, MessageVersion version)
         at SoapCore.MessageEncoder.SoapMessageEncoder.ReadMessageAsync(Stream stream, Int32 maxSizeOfHeaders, String contentType) in /_/src/SoapCore/MessageEncoder/SoapMessageEncoder.cs:line 158
         at SoapCore.MessageEncoder.SoapMessageEncoder.ReadMessageAsync(PipeReader pipeReader, Int32 maxSizeOfHeaders, String contentType) in /_/src/SoapCore/MessageEncoder/SoapMessageEncoder.cs:line 129
         at SoapCore.SoapEndpointMiddleware`1.ReadMessageAsync(HttpContext httpContext, SoapMessageEncoder messageEncoder) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 229
         at SoapCore.SoapEndpointMiddleware`1.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 288
         
         
Someone who can help me please:(
Best regards

**Comment by andersjonsson** [comment]
What does your payload look like?

Easiest way to check that is probably to add an asp.net middleware before adding the soapcore endpoints, to inspect the incoming message. Something like

```
app.Use(async (context, next) =>
{
        context.Request.EnableBuffering();
	var bodyAsText = Encoding.UTF8.GetString(await context.Request.Body.ReadFullyAsync());
	context.Request.Body.Position = 0;
}
```
