### ISSUE TITLE
Exclude members from wsdl

### ISSUE THREAD

**Issue by GO74** [DigDes/SoapCore#99]
I get an exception when trying to call service in order to get wsdl:

```
System.ArgumentException: .NET type ObjectId cannot be resolved into XML schema type
   at SoapCore.MetaBodyWriter.ResolveType(Type type)
   at SoapCore.MetaBodyWriter.AddSchemaType(XmlDictionaryWriter writer, Type type, String name, Boolean isArray, String namespace)
   at SoapCore.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
   at SoapCore.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteBodyContentsAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsync(Message message, Stream stream)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsyncInternal(Message message, Stream stream)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin(Task task)
   at SoapCore.SoapEndpointMiddleware.ProcessMeta(HttpContext httpContext)
   at SoapCore.SoapEndpointMiddleware.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I tried to apply [IgnoreDataMember] and [XmlIgnore], but they seem to be ignored. Any advice is appriciated.

**Comment by kotovaleksandr** [comment]
Using IgnoreDataMember good way, but currently SoapCore don't support them. You can add this feature to MetaBodyWriter.cs and send PR.

**Comment by mircotamburini** [comment]
There's a plan to implement this feature?

**Comment by neilsimp1** [comment]
@kotovaleksandr I've just attempted this with https://github.com/neilsimp1/SoapCore/commit/605b13008575ea41cb2e75b805e6cd6440eff769. I've tested it with my own project and any properties with [IgnoreDataMember] on them were omitted from the WSDL.

Should I submit a PR? There are no tests writted for this since I didn't see anything in the Test project having to do with WSDL generation. Please let me know if I'm wrong, or if you want me to submit that as a PR.

**Comment by kotovaleksandr** [comment]
Hi @neilsimp1 Good, send PR, please

**Comment by neilsimp1** [comment]
Cool, just submitted https://github.com/DigDes/SoapCore/pull/129.

**Comment by kotovaleksandr** [comment]
@neilsimp1 Thanks!
