### ISSUE TITLE
SoapCore Performance Issue with large number of request.

### ISSUE THREAD

**Issue by akshaybheda** [DigDes/SoapCore#990]
I have a soap endpoint which i just migrated from wcf to net 6.0. 

I am using k6 to load test as our application in production gets around 2M req per hr. or 2/3 k req per second.

I saw that the requests are failing . I got the trace 

[System.AggregateException: One or more errors occurred. (The client has disconnected)
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|36_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeReaderStream.ReadInternal(Span`1 buffer)
   at System.IO.Pipelines.PipeReaderStream.ReadByte()
   at System.Xml.EncodingStreamWrapper.ReadBOMEncoding(Boolean notOutOfBand)
   at System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)
   at System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at SoapCore.MessageEncoder.SoapMessageEncoder.ReadMessageAsync(Stream stream, Int32 maxSizeOfHeaders, String contentType) in /_/src/SoapCore/MessageEncoder/SoapMessageEncoder.cs:line 136
   at SoapCore.MessageEncoder.SoapMessageEncoder.ReadMessageAsync(PipeReader pipeReader, Int32 maxSizeOfHeaders, String contentType) in /_/src/SoapCore/MessageEncoder/SoapMessageEncoder.cs:line 130
   at SoapCore.SoapEndpointMiddleware`1.ReadMessageAsync(HttpContext httpContext, SoapMessageEncoder messageEncoder) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 229
   at SoapCore.SoapEndpointMiddleware`1.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider) in /_/src/SoapCore/SoapEndpointMiddleware.cs:line 288](url)

The soap endpoint returns some values from the cache. the response payload must be around 25-30 kb at max.

Do i need to configure any additional things for this to handle large no of requests?

**Comment by andersjonsson** [comment]
Seems like the connection closes before SoapCore is done reading the request message. Hard to tell what the reason of that is.

The number of requests shouldn't be an issue in itself. My own service (using XmlSerializer and not DataContractSerializer) can handle that number of requests while performing more work than getting cached values. To be fair, my response payloads are smaller than what you mention, but I think it should work anyway.

If I were you I'd fork the repo and debug your service using a debug build of SoapCore so you can see what's going on. Might be hard to mimic exactly how k6 calls the service but I'd give it a go.

**Comment by akshaybheda** [comment]
k6 usually uses virtual uses so 1000 virtual users trying to make 2/3 req per second, so it should be around 2-3k requests per second.

**Comment by akshaybheda** [comment]
I will try to see if i can do like perf testing of debug build of soapcore to check whats going on

**Comment by akshaybheda** [comment]
Tried to reproduce it locally but could not, even after adding soapcore to my project and running dev build. I face this issue when i have 3 instances running in my environment of this configuration 
![image](https://github.com/DigDes/SoapCore/assets/22575879/2fbb8689-7aa8-4bb9-a3d5-336d43d899a7)
